version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: capsule
      POSTGRES_PASSWORD: capsule_password
      POSTGRES_DB: capsule_dev
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  migrate:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://capsule:capsule_password@localhost:5432/capsule_dev
    command: ["/app/capsule-migrate"]
    restart: "no"

  api:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    environment:
      DATABASE_URL: postgres://capsule:capsule_password@localhost:5432/capsule_dev
    ports: ["8080:8080"]
    restart: unless-stopped
    command: ["/app/capsule-api"]

  schemaspy:
    image: schemaspy/schemaspy:latest
    depends_on:
      postgres:
        condition: service_healthy
    command: ["-configFile", "/schemaspy.properties"]
    volumes:
      - ./erd:/output
      - ./schemaspy.properties:/schemaspy.properties:ro

volumes:
  db_data:
