name: Feature Request
description: Suggest an idea or enhancement for Capsule
title: "[FEATURE] "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature!

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe the problem you're trying to solve.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered.
      placeholder: Alternatively, we could...

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (blocking current work)
        - High (would significantly improve workflow)
        - Medium (nice to have)
        - Low (minor improvement)
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Estimated Complexity
      description: How complex do you think this feature would be to implement?
      options:
        - Simple (small change, few files affected)
        - Medium (moderate change, multiple components)
        - Complex (large change, significant architecture impact)
        - Unknown

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases where this feature would be helpful.
      placeholder: |
        1. When doing X, this feature would help by...
        2. In scenario Y, this would solve...

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What would need to be true for this feature to be considered complete?
      placeholder: |
        - [ ] Feature does X
        - [ ] Feature handles edge case Y
        - [ ] Documentation is updated

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, mockups, or examples about the feature request.

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided a clear problem statement and proposed solution
          required: true
        - label: This feature aligns with the project's goals and scope
          required: true
